# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias g.='git add .'
alias ga='git commit -a'
alias gp='git push'
alias q='exit'
alias go_nano='cd ~/Desktop/nano'
alias go_vim='cd ~/Desktop/vim'
alias go_emacs='cd ~/Desktop/emacs'
alias go_lv='cd ~/Desktop/LvTextEditor'
