#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = false
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  buffer_index_type = 4 
  windows_index_type = 3
  enable_tabline_filetype_icon = true 
  enable_statusline_mode = true
  statusline_unicode_symbols = true
  # Enable vim compatible mode, avoid changing origin vim key bindings
  vimcompatible = true
  default_indent = 4
  expand_tab = true

# Enable autoco mplete layer
[[layers]]
	name = 'autocomplete'
	auto-completion-return-key-behavior = "nil"
	auto-completion-tab-key-behavior = "smart"

[[layers]]
	name = 'shell'
	default_position = 'top'
	default_height = 40

[[layers]]
	name = "lang#c"
	enable_clang_syntax_highlight = true

[[layers]]
	name = "format"
	format_on_save = true

[[layers]]
	name = "shell"
	default_position = "bottom"
	default_height = 60

[options]
  default_indent = 4  
  expand_tab = false

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#assembly"

[[layers]]
  name = "ui"

[[layers]]
  name = "git"

[[layers]]
  name = "debug"

[[layers]]
  name = 'lang#typescript'
  enable = true

[[custom_plugins]]
  name = 'lilydjwg/colorizer'
  name = 'adamclerk/vim-razor'

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#csharp"
  highlight_types = 1 

[[layers]]
	name = "colorscheme"

[[layers]]
	name = 'foldsearch'

[[layers]]
	name = "tools"

[[layers]]
	name = "ui"

[options]
  statusline_separator = 'arrow'

